#!/usr/bin/env python3
"""Generate golden audit-log CSV fixture for test_replay_audit_log.py (SP-04).

Usage:
    uv run python scripts/gen_golden.py

Writes:
    packages/trading-core/tests/fixtures/golden_audit/2024-06-12.csv

The CSV is generated by running the bar-by-bar engine-path replay loop over
orb_day_bars(date_str="2024-06-12") — the same synthetic fixture used by
test_replay_audit_log.py. Once committed, the golden must match every CI run.
Any intentional audit-log schema change requires regenerating and re-committing
the golden (run with --update-golden in pytest, or re-run this script).

No argparse: the fixture date 2024-06-12 is hard-coded (D-06).
"""

from __future__ import annotations

import asyncio
import csv
import json
import sys
import tempfile
from datetime import timezone
from decimal import Decimal
from pathlib import Path

# Defensive: reconfigure stdout/stderr to UTF-8 BEFORE any module-level import
# (Pitfall 5 — Windows piped-stdout cp1252 trap; mirrors run_backtest.py pattern).
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Make sure `packages/trading-core/src` is on sys.path when invoked outside
# the uv `run` shim (mirrors run_backtest.py pattern).
_REPO_ROOT = Path(__file__).resolve().parent.parent
_SRC = _REPO_ROOT / "packages" / "trading-core" / "src"
if _SRC.exists() and str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

# Prepend tests/ directory so `from fixtures.orb_day import ...` resolves.
_TESTS_DIR = _REPO_ROOT / "packages" / "trading-core" / "tests"
if _TESTS_DIR.exists() and str(_TESTS_DIR) not in sys.path:
    sys.path.insert(0, str(_TESTS_DIR))

import yaml  # noqa: E402

from trading_core.events.models import TOPIC_RISK_DECISIONS  # noqa: E402
from trading_core.execution.paper import PaperExecutor  # noqa: E402
from trading_core.risk.models import RiskConfig, RiskState  # noqa: E402
from trading_core.risk.full_risk_manager import FullRiskManager  # noqa: E402
from trading_core.storage.duckdb_store import DuckDBStore  # noqa: E402
from trading_core.storage.runs import new_run_id  # noqa: E402
from trading_core.strategy.models import StrategyContext  # noqa: E402
from trading_core.strategy.orb import ORBConfig, ORBStrategy  # noqa: E402

from fixtures.orb_day import orb_day_bars  # noqa: E402

# Golden fixture output path
_GOLDEN_DIR = _REPO_ROOT / "packages" / "trading-core" / "tests" / "fixtures" / "golden_audit"
_GOLDEN_CSV = _GOLDEN_DIR / "2024-06-12.csv"

# Audit CSV header — matches DuckDBStore._AUDIT_CSV_HEADER column order.
_AUDIT_CSV_HEADER = ["event_id", "ts_utc", "topic", "entity_id", "reason_code", "payload_json"]

# Hard-coded fixture date (D-06)
_FIXTURE_DATE = "2024-06-12"


async def _generate_golden() -> None:
    """Run the engine-path replay loop over orb_day_bars and write the golden CSV."""
    bars = orb_day_bars(date_str=_FIXTURE_DATE)

    # Use a temporary DuckDB for the replay (the golden is only the CSV output)
    with tempfile.TemporaryDirectory(prefix="gen_golden_") as tmpdir:
        tmp_db = Path(tmpdir) / "gen_golden.duckdb"
        store = DuckDBStore(tmp_db)
        store.ensure_schema()

        try:
            strategy = ORBStrategy(ORBConfig())
            # Load risk config from the same source as replay.py CLI (T-08-03: yaml.safe_load)
            risk_config_path = _REPO_ROOT / "config" / "risk.yaml"
            with risk_config_path.open("r", encoding="utf-8") as _rc_fh:
                risk_config = RiskConfig(**yaml.safe_load(_rc_fh))
            risk_manager = FullRiskManager(config=risk_config, store=store, symbol="SPY")
            executor = PaperExecutor("SPY")

            # Prepare output CSV
            _GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

            # Track counters in a mutable container (avoids nonlocal in inner fn)
            _counters = {"events": 0, "signals": 0}

            with _GOLDEN_CSV.open("w", newline="", encoding="utf-8") as fh:
                writer = csv.writer(fh)
                writer.writerow(_AUDIT_CSV_HEADER)

                def _write_event(
                    ts_utc,
                    topic: str,
                    det_entity_id: str,
                    reason_code: str,
                    payload_json: str,
                ) -> None:
                    """Write one audit row with a deterministic event_id."""
                    det_event_id = f"replay-{_counters['events']:010d}"
                    writer.writerow(
                        [det_event_id, ts_utc.isoformat(), topic, det_entity_id, reason_code, payload_json]
                    )
                    _counters["events"] += 1

                open_position = None
                risk_state = RiskState()

                # Bar-by-bar replay loop (BL-1 gate: snapshot → on_bar → _push_bar)
                for i, bar in enumerate(bars):
                    ctx = StrategyContext(
                        rollover_seam=bar.rollover_seam,
                        warmup_complete=strategy.is_warm(),
                        bar_index=strategy._bar_count,
                        ts_utc=bar.ts_utc,
                        atr=strategy._atr.current,
                        session_vwap=strategy._vwap.current,
                        ema=strategy._ema.current,
                        adr=None,
                    )

                    signal = strategy.on_bar(bar, ctx)
                    strategy._push_bar(bar)  # push AFTER on_bar — look-ahead safety

                    # Check exit on open position
                    if open_position is not None:
                        exit_result = executor.check_exit(
                            side=open_position["side"],
                            entry_price=open_position["entry_price"],
                            stop=open_position["stop"],
                            target=open_position["target"],
                            bar=bar,
                            is_last_rth_bar=(i == len(bars) - 1),
                        )
                        if exit_result is not None:
                            exit_reason, exit_price = exit_result
                            exit_fill = await executor.fill_exit(
                                signal=open_position["entry_signal"],
                                exit_reason=exit_reason,
                                exit_price=exit_price,
                                exit_ts_utc=bar.ts_utc,
                                fill_qty=open_position["fill_qty"],
                            )

                            if open_position["side"] == "long":
                                pnl = (exit_fill.fill_price - open_position["entry_fill_price"]) * Decimal(open_position["fill_qty"])
                            else:
                                pnl = (open_position["entry_fill_price"] - exit_fill.fill_price) * Decimal(open_position["fill_qty"])

                            risk_state = RiskState(
                                realized_pnl_today=risk_state.realized_pnl_today + pnl,
                                open_exposure_dollars=Decimal("0"),
                                drawdown_model=risk_state.drawdown_model,
                            )

                            exit_payload = json.dumps({
                                "exit_reason": exit_reason,
                                "exit_price": str(exit_fill.fill_price),
                                "fill_qty": exit_fill.fill_qty,
                                "pnl": str(pnl),
                            })
                            store.write_audit_event(
                                event_id=new_run_id(),
                                ts_utc=bar.ts_utc,
                                topic="fills",
                                entity_id=open_position["entry_signal"].signal_id,
                                reason_code=exit_reason,
                                payload_json=exit_payload,
                            )
                            _write_event(
                                ts_utc=bar.ts_utc,
                                topic="fills",
                                det_entity_id=open_position["det_signal_id"],
                                reason_code=exit_reason,
                                payload_json=exit_payload,
                            )
                            risk_manager.record_position_closed(open_position["entry_signal"].strategy_id)
                            open_position = None

                    # Process new signal
                    if signal is not None and open_position is None:
                        decision = await risk_manager.check(signal, risk_state)

                        det_sig_id = f"signal-{_counters['signals']:06d}"

                        decision_payload = decision.model_dump_json()
                        _write_event(
                            ts_utc=signal.ts_utc,
                            topic=TOPIC_RISK_DECISIONS,
                            det_entity_id=det_sig_id,
                            reason_code=decision.reason,
                            payload_json=decision_payload,
                        )

                        if decision.approved:
                            next_bar_idx = i + 1
                            if next_bar_idx < len(bars):
                                next_bar = bars[next_bar_idx]
                                entry_fill = await executor.fill_entry(signal, decision, next_bar)

                                if signal.side == "long":
                                    open_exposure = (bar.close - entry_fill.fill_price) * Decimal(entry_fill.fill_qty)
                                else:
                                    open_exposure = (entry_fill.fill_price - bar.close) * Decimal(entry_fill.fill_qty)

                                risk_state = RiskState(
                                    realized_pnl_today=risk_state.realized_pnl_today,
                                    open_exposure_dollars=open_exposure,
                                    drawdown_model=risk_state.drawdown_model,
                                )

                                entry_payload = json.dumps({
                                    "fill_price": str(entry_fill.fill_price),
                                    "fill_qty": entry_fill.fill_qty,
                                    "side": entry_fill.side,
                                    "slippage_ticks": entry_fill.slippage_ticks,
                                })
                                store.write_audit_event(
                                    event_id=new_run_id(),
                                    ts_utc=next_bar.ts_utc,
                                    topic="fills",
                                    entity_id=signal.signal_id,
                                    reason_code="entry_fill",
                                    payload_json=entry_payload,
                                )
                                _write_event(
                                    ts_utc=next_bar.ts_utc,
                                    topic="fills",
                                    det_entity_id=det_sig_id,
                                    reason_code="entry_fill",
                                    payload_json=entry_payload,
                                )

                                risk_manager.record_position_open(
                                    signal.strategy_id,
                                    {
                                        "symbol": "SPY",
                                        "strategy_id": signal.strategy_id,
                                        "side": signal.side,
                                        "qty": entry_fill.fill_qty,
                                        "avg_fill": entry_fill.fill_price,
                                        "mark": next_bar.close,
                                        "stop": signal.stop,
                                        "target": signal.target,
                                        "entry_ts_utc": next_bar.ts_utc,
                                    },
                                )
                                open_position = {
                                    "side": signal.side,
                                    "entry_price": signal.entry,
                                    "entry_fill_price": entry_fill.fill_price,
                                    "stop": signal.stop,
                                    "target": signal.target,
                                    "fill_qty": entry_fill.fill_qty,
                                    "entry_signal": signal,
                                    "det_signal_id": det_sig_id,
                                }

                        _counters["signals"] += 1

                fh.flush()

        finally:
            store.close()

    print(f"Golden fixture written: {_GOLDEN_CSV}")
    print(f"Events written: {_counters['events']}")


if __name__ == "__main__":
    asyncio.run(_generate_golden())
